services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./apps_data/prometheus:/prometheus
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./apps_data/grafana:/var/lib/grafana
    networks:
      - monitoring_network

  flask_app:
    image: flask_app:0.0.1
    container_name: flaskapp
    restart: always
    ports:
      - "5000:5000"
    networks:
    - monitoring_network
    
networks:
  monitoring_network:
     external: true

