{
 "title": "Python Apps Monitor",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(python_info,job)" } },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(flask_exporter_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GET request, status=200",
   "type": "gauge",
   "description": "GET request, status=200",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$endpoint\", status=\"200\", method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST request, status=201",
   "type": "gauge",
   "description": "POST request, status=201",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$endpoint\", status=\"201\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET request, status=404",
   "type": "gauge",
   "description": "GET request, status=404",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$endpoint\", status=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flask_http_request_total [status=200]",
   "type": "timeseries",
   "description": "flask_http_request_total [status=200]",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$endpoint\", status=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flask_http_request_total [status=201]",
   "type": "timeseries",
   "description": "flask_http_request_total [status=201]",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$endpoint\", status=\"201\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flask_http_request_total [status=404]",
   "type": "timeseries",
   "description": "flask_http_request_total [status=404]",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"$endpoint\", status=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flask_http_request_duration_seconds_count [GET, status=200]",
   "type": "timeseries",
   "description": "flask_http_request_duration_seconds_count",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{instance=\"$endpoint\", method=\"GET\", status=\"200\", path=\"/products\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}